name: Upload Azure Data to Storage

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install openpyxl azure-identity azure-mgmt-monitor azure-storage-blob

    - name: Run script to generate Excel file
      run: python test.py

    - name: Upload to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: "."
        source_file: "azure_resources.xlsx"
        container_name: "your-container-name"
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        sync: true
